ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
    GROUP_BY_SCENE: True
    CYCLE: False
PHYSICS_SIMULATOR:
  TYPE: "Sim-Phys"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    ANGULAR_ACCELERATION: 12.56
    ANGULAR_FRICTION: 1.0
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ENABLE_PHYSICS: True
  RGB_SENSOR:
    WIDTH: 720
    HEIGHT: 720
  DEPTH_SENSOR:
    WIDTH: 720
    HEIGHT: 720
TASK:
  TYPE: Nav-Phys
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: PointNav-v1
  SPLIT: val
  DATA_PATH: data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz

VIDEO_OPTION: ["DISK"]
